### ISSUE TITLE
Resource Levels

### ISSUE THREAD

**Issue by oeon** [SLUGIS/intelreport#10]
we need to adjust the colorLegend div for Resource Levels

**old**
Resources > 75%
LEVEL 1: 75% to 50%
LEVEL 2: 50% to 25%
LEVEL 3: < 25%

**new**
LEVEL 1:  > 75%
LEVEL 2: 75% to 50%
LEVEL 3: 50% to 25%
LEVEL 4: < 25%

**Comment by tstan** [comment]
extremely easy fix, am I allowed to do this?

**Comment by kaysabelle** [comment]
Go for it! :)
