### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by oeon** [SLUGIS/intelreport#16]
let's ensure our Google Sheet is backed up in case it becomes corrupted e.g. a user tries to 'adjust' something they shouldn't

**Comment by kaysabelle** [comment]
Where should this be backed up? Would this just be in another folder on the SLUGIS drive? I'm assuming you would just like an editable copy of the original google sheet and the other sheets that parse data from the original sheet.

**Comment by kaysabelle** [comment]
Create a Backup folder on Google Drive for now, with copies of everything.
