### ISSUE TITLE
archive

### ISSUE THREAD

**Issue by oeon** [SLUGIS/intelreport#17]
automate a daily archive of the .xslx that can be available for ECC personnel to access in-case they need to review a specific date in the past.

**Comment by tstan** [comment]
where should the files be stored?

**Comment by tstan** [comment]
Wrote cron job and a few scripts using a pre-written dropbox uploader script. XLSX uploads to _data//Intel_Archive on dropbox, lmk if you want the location changed.

**Comment by oeon** [comment]
very great and awesome work! Let's use Public/admin-reports/ as the location.

**Comment by kaysabelle** [comment]
Updated, on both the server and GitHub. 8d0b78203a51740d1352a9faac9f831d04376506
