### ISSUE TITLE
Not auto populating SLC Engines, or Crews. 

### ISSUE THREAD

**Issue by Chief-Tritip** [SLUGIS/intelreport#23]
I must have messed up the SLC Engines, and the Crews are not populating on the intel report.

**Comment by oeon** [comment]
we made a backup of the intel report for exactly this reason....please backup the backup

**Comment by Chief-Tritip** [comment]
Correction it is the SLU Engines and Crews that are not populating..

**Comment by oeon** [comment]
fixed! now Greg and I know how to revert from the backup.

1) replace **AdminReport ID** in the two lines within the `AdminReport gScript`
2) update the **SHEET KEY** with the **AdminReport ID** within the `INTEL REPORT formatted`
3) allow the `INTEL REPORT formatted` to access the `AdminReport`
