### ISSUE TITLE
Date at the top

### ISSUE THREAD

**Issue by Chief-Tritip** [SLUGIS/intelreport#26]
The date at the top is no longer auto populating.. With current date.

**Comment by tstan** [comment]
Hi Greg,

If you meant the date on the excel sheet, I have replaced the date with an auto-function that excel provides which will automatically change everyday, I'm not sure what happened to it that made it stop automatically filling.

Sorry for all the issues! I'll make sure to fix 'em all when I come back to SLO next week.
