### ISSUE TITLE
AirAttack not reporting on Web

### ISSUE THREAD

**Issue by Chief-Tritip** [SLUGIS/intelreport#28]
The AA340 cell is not reporting on the web intel report when statused on.

**Comment by oeon** [comment]
AIR_ATTACK formula (cell G2 in **INTEL REPORT formatted** Sheet): `=COUNTIF(IMPORTRANGE(A2, "Morning Report!AA19:AA20"), "<>"&"")` needed to read `AA18:AA20` for the AA340 cell in the **AdminReport**/Morning Report worksheet.
